name: Deploy Images to GHCR

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - "master"

env:
  TARGET_PLATFORMS: linux/arm/v7
  REGISTRY: ghcr.io/nicholas-c

jobs:
  push-flood-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './docker/flood'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generate automatically tags <https://github.com/docker/metadata-action>
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/flood
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker
        uses: docker/build-push-action@v2
        with:
          context: './docker/flood'
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.TARGET_PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


  push-rtorrent-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './docker/rtorrent'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generate automatically tags <https://github.com/docker/metadata-action>
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/rtorrent
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker
        uses: docker/build-push-action@v2
        with:
          context: './docker/rtorrent'
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.TARGET_PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
